### PR TITLE
Bump Drupal 7 to PHP 7.1; Fix update.sh so that it can scrape drupal releases again

### LINKED ISSUE #136: Use PHP 7.1 for Drupal 7
The drupal 7 image currently uses php 7.0; however [Drupal 7 now supports 7.1](https://www.drupal.org/docs/7/system-requirements/drupal-7-php-requirements); can we use version 7.1 of PHP as a base image?

### PR DESCRIPTION
**Pull request by yosifkit**
Also run update to bump versions and apply new PHP version.

The update.sh change is a temporary fix to get it to work more often; it needs to be updated again to use the "Releases" API described on https://www.drupal.org/drupalorg/docs/api, but it is only xml. :cry:

Fixes #136

### CODE REVIEW

File: 7/apache/Dockerfile [hunk 1]
```diff
@@ -1,5 +1,5 @@
 # from https://www.drupal.org/docs/8/system-requirements/drupal-8-php-requirements
-FROM php:7.0-apache
+FROM php:7.1-apache
```
Comment (tianon) [inline 7/apache/Dockerfile]: Is this supported on Drupal 7?  The URL here is for 8. 😬

File: update.sh [hunk 2]
```diff
@@ -11,10 +11,10 @@ versions=( "${versions[@]%/}" )
 
 defaultPhpVersion='7.2'
 declare -A phpVersions=(
-	[7]='7.0'
+	[7]='7.1'
 )
 
-curl -fsSL 'https://www.drupal.org/node/3060/release' -o release
+curl -fsSL 'https://www.drupal.org/node/3060/release' -H 'authority: www.drupal.org' -o release
```
Comment (tianon) [inline update.sh]: Lawl 👌

File: 7/apache/Dockerfile (hunk 1 above)
Comment (tianon) [reply 7/apache/Dockerfile]: Ah, https://www.drupal.org/docs/7/system-requirements/drupal-7-php-requirements#php_required is the link you were working from. :+1:

Comment (tianon) [reply 7/apache/Dockerfile]: (This 7.61 release supposedly is the first with PHP 7.2 support, but it does seem a tad aggressive to jump that far right away. :smile:)
